### PR TITLE
Add build workflow

### PR DESCRIPTION
**Pull request by s1204IT**
- Add build workflow
- Always signing with android testkey
- Upgrade Gradle and AGP
  - ~~Please don't upgrade AGP to 8.3~~
- Upgrade compileSdk and targetSdk to 34
- ~~Upgrade minSdk from 19 to 21~~
- Add japanese document

### CODE REVIEW

**Comment by iamr0s** [comment]
please explain:
- Please don't upgrade AGP to 8.3
- Upgrade minSdk from 19 to 21

**Comment by s1204IT** [comment]
> Please don't upgrade AGP to 8.3

Simply put, the build fails.

> Upgrade minSdk from 19 to 21

This is simply because we thought it was unnecessary before Lollipop.  
If Dhizuku features work on Android 4.4, I will revert minSdk.

**Comment by s1204IT** [comment]
> Simply put, the build fails.

No, it looks like the build passed.

**Comment by s1204IT** [comment]
Fixed both issues.

**Comment by iamr0s** [comment]
关于AGP，我后续会检查它为何会失败。

Dhizuku-API的初稿是我用于权限共享设计的，共享Device Owner只是它的一部分。
> 因为在Android中，只有sharedUID可以实现两个应用用相同的uid。而Dhizuku-API可以基于Binder和Process实现两个应用共享uid。

**Comment by s1204IT** [comment]
Well, what does that have to do with closing? If there are any additional points you'd like to correct, I'm open to them.

**Pull request closed without merging**
